spring:
  datasource:
    numportal:
      url: jdbc:postgresql://${DATABASE_SERVER}/${DATABASE_NAME}?currentSchema=num
      driver-class-name: org.postgresql.Driver
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
    numportal-attachment:
      url: jdbc:postgresql://${ATTACHMENT_DATABASE_SERVER}/${ATTACHMENT_DATABASE_NAME}?currentSchema=num
      driver-class-name: org.postgresql.Driver
      username: ${ATTACHMENT_DATABASE_USERNAME}
      password: ${ATTACHMENT_DATABASE_PASSWORD}
  flyway:
    # migration done via configuration files
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
        provider:
          userStoreClient:
            token-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASS}
    from: ${EMAIL_FROM}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_AUTH}
          starttls:
            enabled: ${EMAIL_STARTTLS_ENABLED}
            required: ${EMAIL_STARTTLS_REQUIRED}

management:
  server:
    port: ${MANAGEMENT_PORT}

userstore:
  url: ${KEYCLOAK_ENDPOINT}/auth/admin/realms/${KEYCLOAK_REALM}

swagger:
  oauth2:
    token-uri: ${KEYCLOAK_CANONICAL_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
    auth-uri: ${KEYCLOAK_CANONICAL_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    client-name: ${SWAGGER_OAUTH2_CLIENT-NAME}
    client-secret: ${SWAGGER_OAUTH2_CLIENT-NAME}

ehrbase:
  rest-api-url: ${EHRBASE_ENDPOINT}/ehrbase/
  username: ${EHRBASE_USER}
  password: ${EHRBASE_PASSWORD}

privacy:
  minHits: ${PRIVACY_MIN_HITS}

atna:
  enabled: ${ATNA_ENABLED}
  host: ${ATNA_HOST}
  port: ${ATNA_PORT}

zars:
  enabled: ${ZARS_ENABLED}
  email: ${ZARS_EMAIL}

num:
  url: ${NUM_URL}
  locale: ${NUM_LOCALE}
  systemStatusUrl: ${STATUS_URL}
  userManualUrl:
    DE: ${USER_MANUAL_URL_DE}
    EN: ${USER_MANUAL_URL_EN}
    # if true a second database is configured for attachments - check configs for numportal-attachment
  enableAttachmentDatabase: ${ENABLE_CONNECTION_TO_ATTACHMENT_DATABASE}

consent:
  allow-usage-outside-eu-oid: ${ALLOW_USAGE_OUTSIDE_EU_OID}

fttp:
  url: ${FTTP_URL}
  certificatePath: ${FTTP_CERT_PATH}
  certificateKey: ${FTTP_CERT_PASSWORD}
  useBasicAuth: ${FTTP_USE_BASIC_AUTH}
  username: ${FTTP_USERNAME}
  password: ${FTTP_PASSWORD}

requestpsnworkflow:
  params:
    study: ${PSNWORKFLOW_STUDY}
    source: ${PSNWORKFLOW_SOURCE}
    target: ${PSNWORKFLOW_TARGET}
    apikey: ${PSNWORKFLOW_API_KEY}
    event: ${PSNWORKFLOW_EVENT}

pseudonymity:
  fake3rdPartyPseudonymEnabled: ${FAKE_3RD_PARTY_PSEUDONYM_ENABLED}