server:
  port: 8090
spring:
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=num
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
    user: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
hapi:
  fhir:
    version: r4
    rest:
      server-name: num-portal
      default-response-encoding: json
      default-pretty-print: true
    validation:
      enabled: false
      request-only: true
keycloak-admin:
  authServerUrl: http://localhost:8180/auth
  realm: Num
  client: numPortal
  secret: 3c18c1dc-ba8d-4ab7-9a91-0178130f74ba
keycloak:
  enabled: false

logging:
  level:
    de.vitasystems: trace
    org.springframework.web: trace



