server:
  port: 8090
spring:
  application:
    name: num-portal
  datasource:
    hikari:
      data-source-properties:
        stringtype: unspecified
    url: jdbc:postgresql://localhost:5434/numportal?currentSchema=num
    driver-class-name: org.postgresql.Driver
    username: num-portal
    password: HF1ZidZUQbSFQVN31nM026c8IG9pRLYrKJ6DMoML6XBVOyO2dawbt9CuMtpqai6f
  flyway:
    enabled: false
    user: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/auth/realms/crr/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            authorization-grant-type: client_credentials
            client-id: num-portal
            client-secret: 3e6e93f9-3638-4084-b376-49aebc75accb
        provider:
          userStoreClient:
            token-uri: ${keycloak.url}/auth/realms/crr/protocol/openid-connect/token
  mail:
    host: smtp.gmail.com
    port: 587
    username: numportalwebapp@gmail.com
    password: notPassword
    from: numportalwebapp@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
  health:
    mail:
      enabled: false
  server:
    port: 8091

swagger:
  oauth2:
    token-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/token
    auth-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/auth
    client-name: num-portal-webapp
    client-secret: num-portal-webapp

userstore:
  url: ${keycloak.url}/auth/admin/realms/crr

keycloak:
  url: https://keycloak.pre-prod.num-codex.de

hapi:
  fhir:
    version: r4
    rest:
      server-name: num-portal
      default-response-encoding: json
      default-pretty-print: true
    validation:
      enabled: false
      request-only: true

feign:
  client:
    config:
      numPortal:
        connectTimeout: 1000
        readTimeout: 1200
        loggerLevel: FULL

logging:
  level:
    de.vitasystems: trace
    org.springframework.web: trace

atna:
  enabled: false
  host: 151.80.206.33
  port: 3001

zars:
  enabled: false
  email: foo@foo.bar

# use local ehrbase until we get central one
ehrbase:
  rest-api-url: http://localhost:8082/ehrbase/rest/openehr/v1/
  username: ehrbaseAuth
  password: brigand_OUTWARD*shaken0hydro5bumpy2braze1graffito_warlord8voguish

cors:
  allowedOrigins:
    - "*"
privacy:
  minHits: 30
  pseudonymitySecret: AVmnrinfsVDRigh4QGrsDFbs43a

num:
  url: https://pre-prod.num-codex.de
  locale: en

consent:
  allow-usage-outside-eu-oid: 2.16.840.1.113883.3.1937.777.24.5.1.37

fttp:
  url: https://basic-test-fttp-w.num.med.uni-greifswald.de/ttp-fhir/fhir/dispatcher/$requestPsnWorkflow
  certificatePath: /certificates/fttp.num.p12
  certificateKey: fttp123
  useBasicAuth: true
  username: karlea
  password: test123#


---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=num
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            authorization-grant-type: client_credentials
            client-id: numPortal
            client-secret: 3c18c1dc-ba8d-4ab7-9a91-0178130f74ba
        provider:
          userStoreClient:
            token-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/token
  mvc:
    log-request-details: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: numportalwebapp@gmail.com
    password: notPassword
    from: numportalwebapp@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

swagger:
  oauth2:
    token-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/token
    auth-uri: ${keycloak.url}/auth/realms/Num/protocol/openid-connect/auth
    client-name: numPortalWebapp
    client-secret: numPortalWebapp

userstore:
  url: ${keycloak.url}/auth/admin/realms/Num

keycloak:
  url: http://localhost:8180

feign:
  client:
    config:
      numPortal:
        connectTimeout: 1000
        readTimeout: 1200
        loggerLevel: FULL

logging:
  level:
    de.vitasystems: trace
    org.springframework.web: trace

ehrbase:
  rest-api-url: http://localhost:8080/ehrbase/rest/openehr/v1/
  username: ehrbase-user
  password: SuperSecretPassword

privacy:
  minHits: 1
  pseudonymitySecret: AVmnrinfsVDRigh4QGrsDFbs43a

atna:
  enabled: false
  host: localhost
  port: 514

zars:
  enabled: false
  email: foo@foo.bar

num:
  url: http://localhost:8180
  locale: en
