server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: num-portal
  datasource:
    hikari:
      # properties used for aqlcategory json type
      data-source-properties:
        stringtype: unspecified
    numportal:
      url: jdbc:postgresql://localhost:5432/numportal?currentSchema=num
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
    numportal-attachment:
      url: jdbc:postgresql://localhost:5432/num-attachment?currentSchema=num
      driver-class-name: org.postgresql.Driver
      username: num-attachment
      password: num-attachment
  # migration done via configuration class
  flyway:
    enabled: false
    #    user: postgres
    #    password: postgres
    numportal:
      locations: classpath:db/migration/num-portal
    numportal-attachment:
      locations: classpath:db/migration/num-portal-attachment
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/realms/crr/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            authorization-grant-type: client_credentials
            client-id: num-portal
            client-secret: 89dddc8f-0f25-4faf-a58d-6cda681f6ed3
        provider:
          userStoreClient:
            token-uri: ${keycloak.url}/realms/crr/protocol/openid-connect/token
  mail:
    host: smtp.gmail.com
    port: 587
    username: numportalwebapp@gmail.com
    password: notPassword
    from: numportalwebapp@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  health:
    mail:
      enabled: false
  server:
    port: 8091
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    oauth:
      client-id: num-portal-webapp
      client-secret: num-portal-webapp
swagger:
  oauth2:
    token-uri: ${keycloak.url}/realms/Num/protocol/openid-connect/token
    auth-uri: ${keycloak.url}/realms/Num/protocol/openid-connect
    client-name: num-portal-webapp
    client-secret: num-portal-webapp

userstore:
  url: ${keycloak.url}/admin/realms/crr

keycloak:
  url: ${keycloak.url}

hapi:
  fhir:
    version: r4
    rest:
      server-name: num-portal
      default-response-encoding: json
      default-pretty-print: true
    validation:
      enabled: false
      request-only: true

feign:
  client:
    config:
      numPortal:
        connectTimeout: 1000
        readTimeout: 1200
        loggerLevel: FULL
      keycloak:
        loggerLevel: BASIC

logging:
  level:
    org.springframework.web: info
    # DEBUG enables keycloak feign logging
    org.highmed.numportal.web.feign.KeycloakFeign: INFO
    org.highmed.numportal: INFO


atna:
  enabled: false
  host: 151.80.206.33
  port: 3001

zars:
  enabled: false
  email: foo@foo.bar

# use local ehrbase until we get central one
ehrbase:
  rest-api-url: http://localhost:8080/ehrbase/
  username: ehrbase-user
  password: SuperSecretPassword
  adminUsername: ehrbase-admin
  adminPassword: EvenMoreSecretPassword


cors:
  allowedOrigins:
    - "*"
privacy:
  minHits: 30
  pseudonymitySecret: AVmnrinfsVDRigh4QGrsDFbs43a
  pseudonomityChunksSize: 50

num:
  url: ${NUM_URL}
  locale: en
  userManualUrl:
    DE: 'https://num-portal-webapp.readthedocs.io/de/latest/'
    EN: 'https://num-portal-webapp.readthedocs.io/en/latest/'
  # if true a second database is configured for attachments - check configs for numportal-attachment
  enableAttachmentDatabase: false
  # default PDF file size is 10 MB. 1024*1024*10
  pdfFileSize: 10485760
  fileVirusScanEnabled: true

clamAV:
  host: localhost
  port: 3310
  read-timeout: 35000
  connection-timeout: 2000

consent:
  allow-usage-outside-eu-oid: 2.16.840.1.113883.3.1937.777.24.5.1.37

fttp:
  url: https://basic-test-fttp-w.num.med.uni-greifswald.de/ttp-fhir/fhir/dispatcher/$requestPsnWorkflow
  certificatePath: /certificates/fttp.num.p12
  certificateKey: fttp123
  useBasicAuth: true
  username: karlea
  password: test123#

requestpsnworkflow:
  params:
    study: num
    source: ${PSNWORKFLOW_SOURCE}
    target: extern_
    apikey: iCZdh7ZWuf8ms)vvBgU-IaLi4
    event: num.get_extern_psn

pseudonymity:
  fake3rdPartyPseudonymEnabled: false

user-service:
  delete-users-cron: 0 0 5 * * *