spring:
  datasource:
    url: jdbc:h2:mem:num;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    schemas: num
    url: jdbc:h2:mem:num
hapi:
  fhir:
    version: r4
    rest:
      server-name: num-portal
      default-response-encoding: json
      default-pretty-print: true
    validation:
      enabled: false
      request-only: true
