# Copyright 2021 Vitagroup AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVER}/${DATABASE_NAME}?currentSchema=num
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      client:
        registration:
          userStoreClient:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
        provider:
          userStoreClient:
            token-uri: ${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASS}
    from: ${EMAIL_FROM}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_AUTH}
          starttls:
            enabled: ${EMAIL_STARTTLS_ENABLED}
            required: ${EMAIL_STARTTLS_REQUIRED}

userstore:
  url: ${KEYCLOAK_ENDPOINT}/auth/admin/realms/${KEYCLOAK_REALM}

swagger:
  oauth2:
    token-uri: ${KEYCLOAK_CANONICAL_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
    auth-uri: ${KEYCLOAK_CANONICAL_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
    client-name: ${SWAGGER_OAUTH2_CLIENT-NAME}
    client-secret: ${SWAGGER_OAUTH2_CLIENT-NAME}

ehrbase:
  rest-api-url: ${EHRBASE_ENDPOINT}/ehrbase/rest/openehr/v1/
  username: ${EHRBASE_USER}
  password: ${EHRBASE_PASSWORD}

privacy:
  minHits: ${PRIVACY_MIN_HITS}

atna:
  enabled: ${ATNA_ENABLED}
  host: ${ATNA_HOST}
  port: ${ATNA_PORT}


zars:
  enabled: ${ZARS_ENABLED}
  email: ${ZARS_EMAIL}
