name: Feature Request
description: Feature request for a new / extended functionality
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Background
      description: Describe the context and intention for this enhancement, such as the benefits and impacts on the user.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Enhancement
      description: Provide specific preconditions, steps, requirements or expectations on the proposed enhancement.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Approved
      description: Add any other context or screenshots about the feature request here.
      options:
        - label: I have discussed the topic with Dirk
          required: true
  - type: textarea
    attributes:
      label: Further information
      description: Add additional information, if needed.
    validations:
      required: false