package de.vitagroup.num.domain.model;

public enum ProjectCategories {
  PEDIATRICS,
  SYMPTOMATOLOGY,
  CLASSIFICATION_OF_DISEASE_PROGRESSION,
  DRUG_THERAPIES,
  SURGICAL_THERAPIES,
  TREATMENT_PLAN,
  ALTERNATIVE_THERAPIES,
  PREVENTION,
  DIAGNOSTIC_METHODOLOGY,
  DRUG_SIDE_EFFECTS,
  MICROBIOLOGY,
  PATHOLOGY,
  ONCOLOGY,
  RARE_DISEASES,
  DECISION_SUPPORT,
  COVID19,
  CRITICAL_CARE_MEDICINE,
  QUALITY_MANAGEMENT_MII,
  QUALITY_MANAGEMENT_ROUTINE_CARE,
  LONGITUDINAL_STUDY,
  PROSPECTIVE_STUDY,
  RETROSPECTIVE_STUDY,
  REGISTRY
}
