name: PR into develop
on:
  pull_request_target:
    branches:
      - 'develop'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run unit tests
        run: mvn clean test
      - name: Run integration tests
        run: mvn verify -P integration-tests
        continue-on-error: true
      - name: Save test results
        run: |
          mkdir -p ~/test-results/unit-tests/
          mkdir -p ~/test-results/integration-tests/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/unit-tests/ \;
          find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/integration-tests/ \;
      - name: Run CVE scan
        run: mvn dependency-check:check
      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: target/site/jacoco-merged-test-coverage-report
      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
      - name: Upload unit tests report
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: ~/test-results/unit-tests/
      - name: Upload integration tests report
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-report
          path: ~/test-results/integration-tests/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

  docker:
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: mvn build
      - name: build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/num-portal:develop -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/num-portal:develop
