name: release

on:
  workflow_dispatch:
    branches: [ 'release/**' ]

env:
  RELEASE_VERSION: ''
  DEV_VERSION: ''

jobs:

  read_version:
    runs-on: ubuntu-latest

    outputs:
      DEV_VERSION: ${{ steps.createVersion.outputs.DEV_VERSION}}
      RELEASE_VERSION: ${{ steps.createVersion.outputs.RELEASE_VERSION}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Create new development version
      id: createVersion
      run: |
        RELEASE_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
        echo "Current version: $RELEASE_VERSION"
        MAJOR=`echo $RELEASE_VERSION | cut -d. -f1`
        MINOR=`echo $RELEASE_VERSION | cut -d. -f2`
        
        DEV_VERSION=${MAJOR}.$((MINOR+1)).0-SNAPSHOT
        
        echo
        echo "Release version: $RELEASE_VERSION"
        echo "Develop version: $DEV_VERSION"
        
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> "$GITHUB_OUTPUT"
        echo "DEV_VERSION=${DEV_VERSION}" >> "$GITHUB_OUTPUT"

  update_dev:
    needs: read_version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Create branch to update develop version
      env:
        DEV_VERSION: ${{ needs.read_version.outputs.DEV_VERSION }}
      run: |
        git branch feature/update_develop_${DEV_VERSION}
        
        mvn versions:set -DnewVersion=${DEV_VERSION} versions:commit
        git commit -am "updated development version to ${DEV_VERSION}"
        
        git push --set-upstream origin feature/update_develop_${DEV_VERSION}

    - name: Create PR to merge changes to Develop and update Version
      env:
        RELEASE_VERSION: ${{ needs.read_version.outputs.RELEASE_VERSION }}
      run: |
        gh pr create -B develop --title "Merge release branch '${RELEASE_VERSION} back to develop"
        gh pr review --approve
        gh pr merge --auto --delete-branch --squash

  release:
    needs: read_version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Create branch to update develop version
      env:
        DEV_VERSION: ${{ needs.read_version.outputs.DEV_VERSION }}
      run: mvn versions:set -DremoveSnapshot
    - name: Create PR to merge release branch to main
      env:
        RELEASE_VERSION: ${{ needs.read_version.outputs.RELEASE_VERSION }}
      run: |
        gh pr create -B master --title "Merge release branch '${RELEASE_VERSION}"
        gh pr review --approve
        gh pr merge --auto --delete-branch --squash

  wrong_branch:
    if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/develop'

    runs-on: ubuntu-latest

    steps:
    - name: ERROR
      run: echo 'This workflow only runs on develop branch!'
