name: Simple build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Set some variables for the build
        run: |
          if [ ${{ github.ref }} != 'refs/heads/main' ]; then
            echo "IS NOT main branch"
            echo "BUILD_VERSION=1.0.$GITHUB_RUN_NUMBER-PR" >> $GITHUB_ENV
          else
            echo "IS main branch"
            echo "BUILD_VERSION=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          fi
        shell: bash
      - name: See some values
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "BUILD_VERSION=$BUILD_VERSION"
      - name: Set Build-Version in pom.xml
        run: ./mvnw versions:set -DnewVersion=$BUILD_VERSION
      - name: Build
        run: ./mvnw verify
